### PR TITLE
Import functions from fruitr

### PR DESCRIPTION
**Pull request by ezwelty**
I've added the functionality I had developed for `fruitr`, while also doing some cleaning up. Common name and language parsing is supported for Wikipedia, Wikispecies, and Wikicommons. I also switched out `RCurl` for `curl`, as you suggested.

I took the general strategy to make my own direct calls to the MediaWiki API rather than work through an existing package so that I could cache query results and parse them again later (very useful since parsing the page content involves guesswork). However, it's fine if you prefer to use `WikipediR` instead.

### CODE REVIEW

**Comment by sckott** [comment]
@ezwelty thanks!  I'll have a look and get back asap

**Comment by sckott** [comment]
@ezwelty thanks for this. Can you 

* put your functions in a separate file
* add some tests for the functions

**Comment by ezwelty** [comment]
@sckott There you go.

**Comment by sckott** [comment]
looks good, thanks!

**Pull request merged**
